from turtle import*
setup(900,900)
colormode(255)
bgcolor('black')
width(5)
tracer(2)
hideturtle()
color('white')
def move(x,y):
    penup()
    goto(x,y)
    pendown()
    return
def pizza(size=0.6):
    color('orange','white')
    move(xcor(),ycor()+175*size)
    begin_fill()
    rt(75)
    fd(333*size)
    rt(105)
    fd(173*size)
    rt(105)
    fd(333*size)
    end_fill()
    color('orange')
    move(xcor()-86.5*size,ycor()-320*size)
    seth(340)
    begin_fill()
    for i in range(41):
        fd(4.3*size)
        lt(1)
    end_fill()
    color('red')
    move(xcor()-80*size,ycor()+200*size)
    begin_fill()
    for p in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()-25*size,ycor()-36.5*size)
    begin_fill()
    for c in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()+20*size,ycor()-50.5*size)
    begin_fill()
    for m in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()-10.5*size,ycor()+92*size)
    begin_fill()
    for a in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()+18*size,ycor()-78.5*size)
    begin_fill()
    for w in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()-21*size,ycor()-60*size)
    begin_fill()
    for s in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()-60*size,ycor()-64.5*size)
    seth(90)
    begin_fill()
    for f in range(180):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()+115*size,ycor()+50.7*size)
    seth(195)
    begin_fill()
    for z in range(180):
        rt(1)
        fd(0.25*size)
    end_fill()
    color('black')
    move(xcor()-100*size,ycor()+50*size)
    begin_fill()
    for o in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor()+60*size,ycor()-95*size)
    begin_fill()
    for n in range(360):
        rt(1)
        fd(0.25*size)
    end_fill()
    move(xcor(),ycor()+40*size)
    begin_fill()
    for d in range(360):
        rt(1)
        fd(0.25*size)
    seth(0)
    end_fill()
    update()
    return