import pizzatest as pt
from turtle import*
hideturtle()
tracer(0)
setup(1800,800)
colormode(255)
bgcolor(53,55,0)
def move(x,y):
    penup()
    goto(x,y)
    pendown()
    return
def heart(size=1):
    color('blue','blue')
    begin_fill()
    lt(140)
    fd(111.65*size)
    for Γ in range(200):
        rt(1)
        fd(1*size)
    lt(120)
    for Σ in range(200):
        rt(1)
        fd(1*size)
    fd(111.65*size)
    end_fill()
    seth(0)
    return
def diamond(size=1):
    move(xcor()-31.297*size,ycor()+82.2789*size)
    color('orange','orange')
    begin_fill()
    lt(70)
    fd(100*size)
    rt(140)
    fd(100*size)
    rt(40)
    fd(100*size)
    rt(140)
    fd(100*size)
    end_fill()
    seth(0)
    return
def spade(size=1):
    move(xcor()+4.142*size,ycor()+169.3281*size)
    color('red','red')
    rt(180)
    begin_fill()
    lt(140)
    fd(111.65*size)
    for i in range(200):
        rt(1)
        fd(1*size)
    lt(120)
    for n in range(200):
        rt(1)
        fd(1*size)
    fd(111.65*size)
    end_fill()
    rt(130)
    fd(150*size)
    begin_fill()
    for d in range(70):
        rt(1)
        fd(1*size)
    lt(160)
    fd(76*size)
    lt(160)
    for b in range(70):
        rt(1)
        fd(1*size)
    fd(20*size)
    end_fill()
    seth(0)
    return
def club(size=1):
    move(xcor(),ycor()+50.3391*size)
    color('green','green')
    begin_fill()
    rt(100)
    for l in range(270):
        rt(1)
        fd(1*size)
    lt(135)
    for z in range(250):
        rt(1)
        fd(1*size)
    lt(135)
    for ζ in range(271):
        rt(1)
        fd(1*size)
    lt(171)
    for σ in range(70):
        lt(1)
        fd(1.25*size)
    lt(200)
    fd(96*size)
    rt(160)
    for τ in range(70):
        lt(1)
        fd(1.25*size)
    end_fill()
    seth(0)
    return
def jack(size=1):
    move(xcor()+2,ycor()+135)
    begin_fill()
    for m in range(360):
        lt(1)
        fd(0.7*size)
    end_fill()
    fd(30*size)
    rt(90)
    fd(10*size)
    rt(180)
    move(xcor()-60*size,ycor())
    fd(10*size)
    rt(90)
    fd(30*size)
    rt(90)
    fd(100*size)
    for j in range(120):
        rt(1)
        fd(1*size)
    seth(0)
    return
def queen(size=1):
    move(xcor()+1,ycor()+142)
    begin_fill()
    for q in range(360):
        rt(1)
        fd(1*size)
    end_fill()
    move(xcor(),ycor()-90*size)
    fd(10*size)
    rt(40)
    fd(40*size)
    lt(40)
    fd(10*size)
    seth(0)
    return
def king(size=1):
    move(xcor()-25,ycor()+88)
    begin_fill()
    rt(90) 
    for k in range(2):
        fd(75*size)
        lt(90)
        fd(10*size)
        lt(90)
        fd(75*size)
    end_fill()
    move(xcor()+9*size,ycor())
    lt(45)
    fd(78*size)
    begin_fill()
    for r in range(360):
        rt(1)
        fd(0.2*size)
    end_fill()
    move(xcor()-55*size,ycor()+52*size)
    lt(90)
    fd(78*size)
    lt(180)
    begin_fill()
    for Ç in range(360):
        rt(1)
        fd(0.2*size)
    end_fill()
    seth(0)
    return
suitfun=[spade,heart,club,diamond]
class Card_d:
    suits=['Spades','Hearts','Clubs','Diamonds']
    values=['null','Ace',2,3,4,5,6,7,8,9,10, 'Jack', 'Queen', 'King']
    colors=['red','blue','green','orange']
    #suits are organized in the following way:
    #0=spade
    #1=heart
    #2=club
    #3=diamond
    def __init__(self,suit,val):
        self.face=False
        self.suit=suit
        self.val=val
        return
    def info(self):
        print('the suits; spades, hearts, clubs, diamond are represented by the numbers; 0, 1, 2, 3')
        print('this card is the {} of {}.'.format(self.value[self.val],self.suits[self.suit]))
    def draw_f(self):
        move(xcor()+6,ycor())
        color('black','white')
        width(4)
        begin_fill()
        for Φ in range(2):
            fd(138)
            for r in range(90):
                fd(0.105)
                rt(1)
            fd(208)
            for e in range(90):
                fd(0.105)
                rt(1)
        end_fill()
        move(xcor()-6,ycor())
        if self.face==False:
            move(xcor()+73.5,ycor()-115)
            self.drawback()
        if self.face==True:
            self.drawface()
        return
    def drawback(self):
        pt.pizza()
        update()
    def drawface(self):
        seth(0)
        x=xcor()
        y=ycor()
        if self.val==1:
            move(x+75,y-130)
            suitfun[self.suit](0.35)
            move(x+5.5,y-30)
            write('A',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('A',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==2:
            move(x+72,y-60)
            suitfun[self.suit](0.2)
            move(x+74,y-190)
            suitfun[self.suit](0.2) 
            move(x+5.5,y-30)
            write('2',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('2',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==3:
            move(x+72,y-60)
            suitfun[self.suit](0.2)
            move(x+72,y-190)
            suitfun[self.suit](0.2)
            move(x+72,y-127)
            suitfun[self.suit](0.2)
            move(x+5.5,y-30)
            write('3',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('3',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==4:
            move(x+40,y-85)
            suitfun[self.suit](0.18)
            move(x+110,y-85)
            suitfun[self.suit](0.18)
            move(x+40,y-165)
            suitfun[self.suit](0.18)
            move(x+110,y-165)
            suitfun[self.suit](0.18) 
            move(x+5.5,y-30)
            write('4',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('4',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==5:
            move(x+40,y-85)
            suitfun[self.suit](0.18)
            move(x+74,y-124)
            suitfun[self.suit](0.18)
            move(x+110,y-85)
            suitfun[self.suit](0.18)
            move(x+40,y-165)
            suitfun[self.suit](0.18)
            move(x+110,y-165)
            suitfun[self.suit](0.18) 
            move(x+5.5,y-30)
            write('5',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('5',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==6:
            move(x+40,y-80)
            suitfun[self.suit](0.18)
            move(x+110,y-80)
            suitfun[self.suit](0.18)
            move(x+40,y-125)
            suitfun[self.suit](0.18)
            move(x+110,y-125)
            suitfun[self.suit](0.18) 
            move(x+40,y-170)
            suitfun[self.suit](0.18)
            move(x+110,y-170)
            suitfun[self.suit](0.18) 
            move(x+5.5,y-30)
            write('6',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('6',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==7:
            move(x+40,y-80)
            suitfun[self.suit](0.18)
            move(x+110,y-80)
            suitfun[self.suit](0.18)
            move(x+40,y-125)
            suitfun[self.suit](0.18)
            move(x+110,y-125)
            suitfun[self.suit](0.18) 
            move(x+40,y-170)
            suitfun[self.suit](0.18)
            move(x+75,y-205)
            suitfun[self.suit](0.18)
            move(x+110,y-170)
            suitfun[self.suit](0.18) 
            move(x+5.5,y-30)
            write('7',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('7',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==8:
            move(x+40,y-80)
            suitfun[self.suit](0.18)
            move(x+75,y-45)
            suitfun[self.suit](0.18)
            move(x+110,y-80)
            suitfun[self.suit](0.18)
            move(x+40,y-125)
            suitfun[self.suit](0.18)
            move(x+110,y-125)
            suitfun[self.suit](0.18) 
            move(x+40,y-170)
            suitfun[self.suit](0.18)
            move(x+75,y-205)
            suitfun[self.suit](0.18)
            move(x+110,y-170)
            suitfun[self.suit](0.18) 
            move(x+5.5,y-30)
            write('8',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('8',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==9:
            move(x+40,y-80)
            suitfun[self.suit](0.15)
            move(x+75,y-45)
            suitfun[self.suit](0.15)
            move(x+110,y-80)
            suitfun[self.suit](0.15)
            move(x+30,y-125)
            suitfun[self.suit](0.15)
            move(x+75,y-125)
            suitfun[self.suit](0.15)
            move(x+120,y-125)
            suitfun[self.suit](0.15) 
            move(x+40,y-170)
            suitfun[self.suit](0.15)
            move(x+75,y-205)
            suitfun[self.suit](0.15)
            move(x+110,y-170)
            suitfun[self.suit](0.15) 
            move(x+5.5,y-30)
            write('9',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('9',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==10:
            move(x+40,y-70)
            suitfun[self.suit](0.13)
            move(x+74,y-85)
            suitfun[self.suit](0.13)
            move(x+110,y-70)
            suitfun[self.suit](0.13)
            move(x+40,y-105)
            suitfun[self.suit](0.13)
            move(x+110,y-105)
            suitfun[self.suit](0.13) 
            move(x+40,y-138)
            suitfun[self.suit](0.13)
            move(x+74,y-155)
            suitfun[self.suit](0.13)
            move(x+110,y-138)
            suitfun[self.suit](0.13)
            move(x+40,y-170)
            suitfun[self.suit](0.13)
            move(x+110,y-170)
            suitfun[self.suit](0.13) 
            move(x+5.5,y-30)
            write('10',False,align='left',font=('courier',20,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+117,y-225)
            write('10',False,align='left',font=('courier',20,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==11:
            color('black',self.colors[self.suit])
            move(x+75,y-200)
            jack(0.5)
            move(x+5.5,y-30)
            color(self.colors[self.suit])
            write('J',False,align='left',font=('courier',23,'bold'))
            move(x+14,y-43.7)
            suitfun[self.suit](0.1)
            move(x+128,y-225)
            write('J',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-190)
            suitfun[self.suit](0.1)
        if self.val==12:
            color('black',self.colors[self.suit])
            move(x+75,y-200)
            queen(0.5)
            move(x+5.5,y-30)
            color(self.colors[self.suit])
            write('Q',False,align='left',font=('courier',23,'bold'))
            move(x+14.789,y-49)
            suitfun[self.suit](0.1)
            move(x+128,y-222)
            write('Q',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-187)
            suitfun[self.suit](0.1)
        if self.val==13:
            color('black',self.colors[self.suit])
            move(x+75,y-200)
            king(0.5)
            move(x+5.5,y-30)
            color(self.colors[self.suit])
            write('K',False,align='left',font=('courier',23,'bold'))
            move(x+14.789,y-49)
            suitfun[self.suit](0.1)
            move(x+128,y-222)
            write('K',False,align='left',font=('courier',23,'bold'))
            move(x+135,y-187)
            suitfun[self.suit](0.1)
        return